# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9167fc9502aa8c746c2bbc23b2087e84f4785cbf6d4ebe4d0f706ed6ecb041e08cd0078b945790a36193299ee0b0e74053530db50809924f34f04918e8b249

test:
  secret_key_base: 769fd5fb01b907645e9e1a289e320f3c7c2e84040225c20ba36a85a8e860b479f52161cc9f4973d38a630de225e5d1dcf0c1486778454e2007c2b239317e0dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
